<a href="https://colab.research.google.com/github/Prashanti2004/IITP_AIMLT_26011514_Messy_Car_Data_Assignment/blob/main/car_data_MAE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Task 1 — Explore and Identify Issues

In [ ]:
import pandas as pd

df = pd.read_csv("/content/used_cars_messy.csv")

print(df.shape)
print(df.info())
print(df.describe(include='all'))

(15661, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB
None
          Unnamed: 0     car_name   brand  model   vehicle_age km_driven  \
count   15661.000000        15661   15661  15661  15661.000000     15661
unique           NaN          121      80    120           NaN      3868
top              NaN  Hyundai i20  Maruti    i20           NaN     50000
freq             NaN          919    4950    919           NaN       554
mean     9808.189643          NaN     NaN    NaN      6.036843       NaN
std      5642.981540          NaN     NaN    NaN      3.015072       NaN
min         0.000000          NaN     NaN    NaN      0.000000       NaN
25%      4901.000000          NaN     NaN    NaN      4.000000       NaN
50%      9858.000000          NaN     NaN    NaN      6.000000       NaN
75%     14666.000000          NaN     NaN    NaN      8.000000       NaN
max     19543.000000          NaN     NaN    NaN     29.000000       NaN

       seller_type fuel_type transmission_type mileage        engine  \
count        15661     15661             15661   14376  13792.000000
unique           9        14                 2     512           NaN
top         Dealer    Petrol            Manual    18.9           NaN
freq          9614      7465             12424     570           NaN
mean           NaN       NaN               NaN     NaN   1480.489342
std            NaN       NaN               NaN     NaN    511.446057
min            NaN       NaN               NaN     NaN    793.000000
25%            NaN       NaN               NaN     NaN   1197.000000
50%            NaN       NaN               NaN     NaN   1248.000000
75%            NaN       NaN               NaN     NaN   1582.000000
max            NaN       NaN               NaN     NaN   6592.000000

           max_power         seats  selling_price
count   14862.000000  15218.000000   1.550300e+04
unique           NaN           NaN            NaN
top              NaN           NaN            NaN
freq             NaN           NaN            NaN
mean      100.513582      5.324418   1.032764e+06
std        42.854632      0.805993   1.607380e+07
min        38.400000      0.000000   5.000000e+02
25%        74.000000      5.000000   3.850000e+05
50%        88.500000      5.000000   5.550000e+05
75%       117.300000      5.000000   8.250000e+05
max       626.000000      9.000000   1.000000e+09

#Task 2 — Clean the Data

In [ ]:
df = df.dropna(subset=['selling_price'])
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [ ]:
df['brand'] = df['brand'].str.strip().str.lower()
df['brand']

0           renault
1            maruti
2             honda
3          mahindra
4          mahindra
            ...
15656        maruti
15657    volkswagen
15658        maruti
15659       hyundai
15660        maruti
Name: brand, Length: 15503, dtype: object

In [ ]:
df['mileage'] = df['mileage'].str.extract('(\d+\.?\d*)').astype(float)
df['mileage']

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_1438/2350686311.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['mileage'] = df['mileage'].str.extract('(\d+\.?\d*)').astype(float)

0        19.87
1        33.54
2          NaN
3        15.40
4        16.00
         ...
15656    20.77
15657    16.09
15658    20.51
15659    18.60
15660    20.28
Name: mileage, Length: 15503, dtype: float64

In [ ]:
df['mileage'].fillna(df['mileage'].median(), inplace=True)
df.fillna(df.mode().iloc[0], inplace=True)

/tmp/ipykernel_1438/148067408.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mileage'].fillna(df['mileage'].median(), inplace=True)

In [ ]:
df = df.drop_duplicates()
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,honda,City,3,48959,Dealer,Petrol,Manual,19.67,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.40,2179.0,74.00,8.0,925000.0
4,14160,Mahindra XUV500,mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,1197.0,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,hyundai,i20,2,15000,Dealer,Petrol,Manual,18.60,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

#Task 3 — Compute Baseline MAE

In [ ]:
from sklearn.metrics import mean_absolute_error

mean_price = df['selling_price'].mean()

df['baseline_pred'] = mean_price

mae = mean_absolute_error(df['selling_price'], df['baseline_pred'])

print("Baseline MAE:", mae)

Baseline MAE: 867382.2867031656

/tmp/ipykernel_1438/3078731250.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['baseline_pred'] = mean_price